#!/bin/sh

echo $PWD

if [ $1 == "test" ]
then
    exec python -m unittest tests/test_unit.py
fi

if [ $1 == "encode" ]
then
  exec venv/bin/python src/Encoder/Encoder.py
fi

if [ $1 == "decode" ]
then
  exec venv/bin/python src/Decoder/Decoder.py
fi

if [ $1 == "-h" ]
then
  echo "Please use [test, encode, decode, -h]"
fi
